#!/usr/bin/env python3
import venv
import os
import sys
import functools
from subprocess import check_call, check_output
from pathlib import Path

VENV_DIR = Path(".venv")
REQUIREMENTS_FILE = Path("requirements.txt")
if os.name == "nt":
    PYTHON_PATH = Path(VENV_DIR, "Scripts", "python.exe")
    PIP_PATH = Path(VENV_DIR, "Scripts", "pip.exe")
else:
    PYTHON_PATH = Path(VENV_DIR, "bin", "python")
    PIP_PATH = Path(VENV_DIR, "bin", "pip")

def create_venv():
    if not PYTHON_PATH.exists():
        builder = venv.EnvBuilder(with_pip=True)
        builder.create(VENV_DIR)

def install_packages():
    if REQUIREMENTS_FILE.exists():
        check_call([PIP_PATH, "--no-cache-dir", "install", "-r", REQUIREMENTS_FILE])

def get_installed_packages():
    output = check_output([PIP_PATH, "--no-cache-dir", "freeze"], text=True)
    return output.splitlines(keepends=True)

def get_required_packages():
    if not REQUIREMENTS_FILE.exists():
        return list()    
    with REQUIREMENTS_FILE.open() as reqs:
        return reqs.read().splitlines(keepends=True)

def write_packages(packages):
    with REQUIREMENTS_FILE.open("w") as reqs:
        reqs.writelines(packages)

def run_as_src_user(f):
    @functools.wraps(f)
    def wrapper(*args, **kwargs):
        if os.name == "nt":
            return f(*args, **kwargs)
        
        uid, gid = os.getuid(), os.getgid()
        src_perms = os.stat(Path("src"))
        if uid == 0 and gid == 0:
            os.setegid(src_perms.st_gid)
            os.seteuid(src_perms.st_uid)
            result = f(*args, **kwargs)
            os.setegid(gid)
            os.seteuid(uid)
        else:
            result = f(*args, **kwargs)
        return result
    
    return wrapper

@run_as_src_user
def main():
    create_venv()
    installed = get_installed_packages()
    required = get_required_packages()

    if installed != required:
        installed_set = set(installed)
        required_set = set(required)
        if required_set - installed_set:
            install_packages()
        else:
            write_packages(installed)

if __name__ == "__main__":
    main()
    os.execv(PYTHON_PATH, [PYTHON_PATH, "scripts/build/cli.py", *sys.argv[1:]])