# TARGET CONFIG
set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_PROCESSOR arm64)

set(CMAKE_SYSROOT ${CMAKE_SOURCE_DIR}/build/sysroot/osx64/osxcross/SDK/MacOSX26.1.sdk)
set(CMAKE_FIND_ROOT_PATH ${CMAKE_SYSROOT})

# COMPILER CONFIG
set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})

set(CMAKE_C_COMPILER_TARGET arm64-apple-darwin-macho)
set(CMAKE_CXX_COMPILER_TARGET arm64-apple-darwin-macho)
set(CMAKE_OBJC_COMPILER_TARGET arm64-apple-darwin-macho)
set(CMAKE_OBJCXX_COMPILER_TARGET arm64-apple-darwin-macho)
set(CMAKE_ASM_COMPILER_TARGET arm64-apple-darwin-macho)

set(CMAKE_C_FLAGS_INIT "--sysroot=${CMAKE_SYSROOT}" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_INIT "--sysroot=${CMAKE_SYSROOT}" CACHE STRING "" FORCE)
set(CMAKE_OBJC_FLAGS_INIT "--sysroot=${CMAKE_SYSROOT}" CACHE STRING "" FORCE)
set(CMAKE_OBJCXX_FLAGS_INIT "--sysroot=${CMAKE_SYSROOT}" CACHE STRING "" FORCE)

set(MACTOOLS_DIR ${CMAKE_SOURCE_DIR}/build/sysroot/osx64/osxcross/bin)
set(CMAKE_INSTALL_NAME_TOOL ${MACTOOLS_DIR}/arm64-apple-darwin25.1-install_name_tool CACHE FILEPATH "install_name_tool" FORCE)
set(CMAKE_RANLIB ${MACTOOLS_DIR}/arm64-apple-darwin25.1-ranlib CACHE FILEPATH "ranlib" FORCE)
set(CMAKE_OSX_DEPLOYMENT_TARGET "11.0" CACHE STRING "osx minimum deployment target" FORCE)

# PACKAGE LOCATION CONFIG
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# CONDITIONAL COMPILATION VARIABLES
add_compile_definitions(CONTROLLER_TARGET="MAC")

# DISABLED LIBS
set(DISABLE_SDL true)
set(DISABLE_CURL true)