# TODO: fix redundant rebuilds when using this toolchain 

# TARGET CONFIG
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm64)

set(CMAKE_SYSROOT ${CMAKE_SOURCE_DIR}/build/sysroot/rpi64)
set(CMAKE_FIND_ROOT_PATH ${CMAKE_SYSROOT})

# COMPILER CONFIG
set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})

set(CMAKE_C_COMPILER_TARGET arm64-linux-gnu)
set(CMAKE_CXX_COMPILER_TARGET arm64-linux-gnu)
set(CMAKE_ASM_COMPILER_TARGET arm64-linux-gnu)

# LINKER CONFIG
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} --sysroot=${CMAKE_SYSROOT}" CACHE INTERNAL "" FORCE)
SET(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} --sysroot=${CMAKE_SYSROOT}" CACHE INTERNAL "" FORCE)
SET(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} --sysroot=${CMAKE_SYSROOT}" CACHE INTERNAL "" FORCE)

# PACKAGE LOCATION CONFIG
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# CONDITIONAL COMPILATION VARIABLES
add_compile_definitions(CONTROLLER_TARGET="RPI64")
add_compile_definitions(__RPI64__)

# DISABLED LIBS
set(DISABLE_SDL true)
set(DISABLE_CURL true)

# REQUIRED LIBS
set(SYSTEM_LINK_LIBRARIES pigpio)