# TARGET CONFIG
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_SYSROOT /win64)
set(CMAKE_FIND_ROOT_PATH ${CMAKE_SYSROOT})

# COMPILER CONFIG
set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})
set(CMAKE_RC_COMPILER x86_64-w64-mingw32ucrt-windres)

set(CMAKE_C_COMPILER_TARGET x86_64-w64-mingw32ucrt)
set(CMAKE_CXX_COMPILER_TARGET x86_64-w64-mingw32ucrt)
set(CMAKE_ASM_COMPILER_TARGET x86_64-w64-mingw32ucrt)

set(CMAKE_C_FLAGS_INIT   "--sysroot=${CMAKE_SYSROOT} -Wno-unused-command-line-argument" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_INIT "--sysroot=${CMAKE_SYSROOT}" CACHE STRING "" FORCE)

# LINKER CONFIG
# Statically compile to avoid packaging with mingw64 dlls 
add_link_options(-static-libgcc -static-libstdc++ --static -lwinpthread -lws2_32 -lmswsock)

# PACKAGE LOCATION CONFIG
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# CONDITIONAL COMPILATION VARIABLES
add_compile_definitions(CONTROLLER_TARGET="WINDOWS")
add_compile_definitions(BOOST_ALL_NO_LIB)

# DISABLED LIBS
set(DISABLE_CURL true)