name: Access Cache

on:
    schedule:
        - cron: 0 0 * * 0
          timezone: America/New_York
    workflow_dispatch:

jobs:
    access-cache:
        permissions:
            contents: read
            actions: read
        strategy:
            matrix:
                platform: [linux64, rpi64, win64, osx64, wasm32-web, wasm32-node]
        env:
            PROJECT_PREFIX: bls
            FILE_GLOB: |
                src/**
                test/**
                config/**
                .cmake/**
                CMakeLists.txt
                .env
        runs-on: ubuntu-latest
        steps:
            -
                name: Access Build Cache
                uses: actions/cache/restore@v5
                with:
                    key: ${{ env.PROJECT_PREFIX }}-build-${{ matrix.platform }}-${{ github.ref_name }}-${{ hashFiles(env.FILE_GLOB) }}
                    path: |
                        ./.cdeps
                        ./build

            -
                name: Access CCache Volume
                uses: rit628/docker-volume-cache-action/restore@main
                with:
                    key: ${{ env.PROJECT_PREFIX }}-ccache-${{ matrix.platform }}-${{ github.ref_name }}-${{ hashFiles(env.FILE_GLOB) }}
                    volumes: |
                        ${{ env.PROJECT_PREFIX }}_ccache